### ISSUE TITLE
Config set up fine but not giving player count

### ISSUE THREAD

**Issue by jevburns** [GravityWolfNotAmused/PlayerCountDiscordBot#1]
Hi there. Many thanks for your hard work! I have come across an error where on discord its saying that its watching my ip address and port number. But no player count is showing. 
![Boterror](https://user-images.githubusercontent.com/80871414/112318634-2bf68200-8ca5-11eb-92c8-3d085532132b.JPG)

**Comment by jevburns** [comment]
thanks i have fixed it myself. Sorry to bother you . Jev

**Comment by GravityWolfNotAmused** [comment]
@jevburns I am sorry, I was at work when you had put this is, but I believe that your issue had to be that you were using the steam game port, and not the query port. I always go through my github issues after my work day, so if you by chance do not figure it out by that time, I am always glad to look further into it. Also, I will be setting up issue templates, and everything for this project, so in the future you will have a format that will help you understand the information that I require, and some of the information would have to be sent privately.

Best wishes,

Larry

**Comment by jevburns** [comment]
Hi Larry, Many thanks for the reply and really appreciate the time you have taken to get back to me. I’m very new to dayz and have just set up a server myself and I have added the bot into my discord channel now and it works a treat. Really thankful for that! I have switched up from being a player to learning how to code and understand the stuff behind the game so far and it’s been very interesting.  Thanks again, Jevon Burns  Sent from Mail for Windows 10 From: LarrySent: 24 March 2021 22:06To: GravityWolfNotAmused/PlayerCountDiscordBotCc: jevburns; MentionSubject: Re: [GravityWolfNotAmused/PlayerCountDiscordBot] Config set up fine but not giving player count ***@***.*** I am sorry, I was at work when you had put this is, but I believe that your issue had to be that you were using the steam game port, and not the query port. I always go through my github issues after my work day, so if you by chance do not figure it out by that time, I am always glad to look further into it. Also, I will be setting up issue templates, and everything for this project, so in the future you will have a format that will help you understand the information that I require, and some of the information would have to be sent privately.Best wishes,Larry—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by GravityWolfNotAmused** [comment]
Well welcome to the DayZ community, and I hope to have more useful "host it yourself" utilities to make things easier for the community in the close future, so stay tuned. I would offer to help you understand; however, recently I have had to step back, and think about my own mental and social health, so I do not offer such help anymore. All I can say, if you stick with programming and learn each concept as purely a concept, and that is not something that may not be specific to that language, but possibly to all languages, you will easily learn your first, and then your second programming language as I did ~6 years ago. In the end, it's just syntax/grammar.

Please submit any new issues you may be facing as another issue. I did have crash issues from steam not replying sometimes, and you will see those are red messages you will see at some point in use; however, these exceptions should be solved and should only have to wait for steam to reply back on the next update sync. Also understand, I am always hunting down crash issues when they are presented to me in a decent format, and the discord bot will generate a crash file inside the folder location for the application.

Best Wishes
