### ISSUE TITLE
[BUG] Release 1.0.6.1 Missing System.Security.Cryptography.ProtectedData

### ISSUE THREAD

**Issue by TheGamingChief** [GravityWolfNotAmused/PlayerCountDiscordBot#13]
**Describe the bug**
In the most recent release (1.0.6.1) when you run DiscordPlayerCountBot.exe the window will just close and no errors are displayed. If you run DiscordPlayerCountBot.exe in Powershell you get the following error.

`PS C:\Users\UserName\Desktop\test> .\DiscordPlayerCountBot.exe
Error:
  An assembly specified in the application dependencies manifest (DiscordPlayerCountBot.deps.json) was not found:
    package: 'System.Security.Cryptography.ProtectedData', version: '4.5.0'
    path: 'runtimes/win/lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll'
PS C:\Users\UserName\Desktop\test>`

This issue does not happen in version 1.0.6 as runtimes/win/lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll is included in this version.

**To Reproduce**
1. Download version 1.0.6.1 of DiscordPlayerCountBot.zip from [here](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/releases/tag/1.0.6.1).
2. Run DiscordPlayerCountBot.exe
3. Window will close with no error, if you run DiscordPlayerCountBot.exe via Powershell you get the error stated above.

**Expected behavior**
Application should launch, see there is no config file, create config file, and request the user to restart the program after setting up the config file.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1

N/A

**Comment by GravityWolfNotAmused** [comment]
@TheGamingChief 

I have grabbed the 1.0.6.1 release and followed your steps, and I cannot recreate this issue.

When following your information, the config file generates as intended,
The bot works after configured,
the mentioned DLL is packaged with the application and is located in the dependencies manifest.

Any chance you have a moment to meet up and see what might be going on?

**Comment by GravityWolfNotAmused** [comment]
@TheGamingChief Give me a moment, @Specker informed me that I hadn't pushed a release with his recent changes.

**Comment by GravityWolfNotAmused** [comment]
[DiscordPlayerCountBot.zip](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/files/7892776/DiscordPlayerCountBot.zip)

**Comment by TheGamingChief** [comment]
@GravityWolfNotAmused It looks like that version you just attached with the runtimes folder included is working as expected and I no longer get that error.

**Comment by GravityWolfNotAmused** [comment]
This was a mistake on my part, @TheGamingChief. 

The last releases ZIP has been updated.
https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/releases/tag/1.0.6.1


Thank you for the report 👍
