### ISSUE TITLE
Bot does not launch from CMD file

### ISSUE THREAD

**Issue by tboy1337** [GravityWolfNotAmused/PlayerCountDiscordBot#16]
Attempting to launch the bot via a CMD file will result in the bot window opening with no text displayed and the discord bot does not display the current players, after closing and opening manually it will work, find below the launch method im using:

START C:\"PATH TO EXE"\DiscordPlayerCountBot.exe

**Comment by GravityWolfNotAmused** [comment]
No text, and nothing in the warnings and errors file?

**Comment by tboy1337** [comment]
exactley yes

**Comment by GravityWolfNotAmused** [comment]
![image](https://user-images.githubusercontent.com/24533882/163029720-e42cf1ce-d879-45b9-9701-dd0b2c5e7be9.png)

**Comment by GravityWolfNotAmused** [comment]
Looks like it works for me, friend. Must be something specific about your file system's permissions, or something specific you are doing differently.

Can you share your batch script with me?

**Comment by tboy1337** [comment]
:LOOP
START C:\pzserver\StartServer64_MOD.bat
TIMEOUT /T 900
START C:\Users\SERVER\Desktop\PZ\scripts\set_prio.cmd
TIMEOUT /T 3
START C:\Users\SERVER\Desktop\PZ\PlayerCountBot\DiscordPlayerCountBot.exe
TIMEOUT /T 43200
START /wait C:\Users\SERVER\Desktop\PZ\scripts\quit.exe
TIMEOUT /T 3
START /wait C:\Users\SERVER\Desktop\PZ\scripts\kill.cmd
TIMEOUT /T 3
START /wait C:\Users\SERVER\Desktop\PZ\scripts\update_pze.cmd
TIMEOUT /T 15
GOTO LOOP

**Comment by GravityWolfNotAmused** [comment]
If you run specifically: START C:\Users\SERVER\Desktop\PZ\PlayerCountBot\DiscordPlayerCountBot.exe

What does it do?

**Comment by tboy1337** [comment]
it launches the player bot with a blank window, im running all thse with a .cmd extension btw

**Comment by tboy1337** [comment]
just tried it as .bat, same thing.

**Comment by tboy1337** [comment]
and same thing when i launch it from an already running CMD window

**Comment by GravityWolfNotAmused** [comment]
It seems to be a system pathing issue.


I tried this on my side, and this happens when I try to start the application from outside of the directory.
![image](https://user-images.githubusercontent.com/24533882/163030887-443bd516-0002-4790-8d72-37dcde6f0163.png)

**Comment by GravityWolfNotAmused** [comment]
Where is this cmd/batch file located in comparison to your bot's executable?

**Comment by tboy1337** [comment]
how would i solve this?

**Comment by tboy1337** [comment]
main launch CMD is in C:\Users\SERVER\Desktop\PZ\scripts, bot is in C:\Users\SERVER\Desktop\PZ\PlayerCountBot

**Comment by GravityWolfNotAmused** [comment]
Can you try CDing to the location of the bot before starting it?

**Comment by GravityWolfNotAmused** [comment]
```
cd C:\Users\SERVER\Desktop\PZ\PlayerCountBot
start PlayerCountDiscordBot.exe
```

**Comment by tboy1337** [comment]
yes that worked thanks, how would i add this to a batch file?

**Comment by tboy1337** [comment]
ah ok so that will work, 2 seconds i will try it.

**Comment by GravityWolfNotAmused** [comment]
```
:LOOP
START C:\pzserver\StartServer64_MOD.bat
TIMEOUT /T 900
START C:\Users\SERVER\Desktop\PZ\scripts\set_prio.cmd
TIMEOUT /T 3
cd C:\Users\SERVER\Desktop\PZ\PlayerCountBot
START DiscordPlayerCountBot.exe
TIMEOUT /T 43200
cd C:\Users\SERVER\Desktop\PZ\scripts
START /wait quit.exe
TIMEOUT /T 3
START /wait kill.cmd
TIMEOUT /T 3
START /wait update_pze.cmd
TIMEOUT /T 15
GOTO LOOP
```

**Comment by tboy1337** [comment]
amazing thanks xD

**Comment by GravityWolfNotAmused** [comment]
Welcome, just tell me if this works, and I will close the issue.

**Comment by tboy1337** [comment]
yes its working now.

**Comment by GravityWolfNotAmused** [comment]
> yes its working now.

Awesome! Enjoy <3
