### ISSUE TITLE
dynamic ip addresses[IDEA]

### ISSUE THREAD

**Issue by Tesch1933** [GravityWolfNotAmused/PlayerCountDiscordBot#5]
First of all....wow, great, worked immediately! Thank you!
I have a question...
My IP changes every day. 
Is there a way to read it automatically (for example via a website like "whats my ip") and update it automatically?
Thanks!

**Comment by GravityWolfNotAmused** [comment]
Hello @Tesch1933,

Can you please explain to me why your IP changes daily? I don't quite understand why someone would have such a thing set up.


The only thing that I think can do is allow users to use `localhost`, or `hostmachine` inside of their configs, and automatically resolve to whichever IP that C# ends up getting. I'd have to do some research to see what all is possible within the grounds of the language I am writing in, but I am willing to do that, so please answer my question above.

Thanks,
Larry/GravityWolf

**Comment by GravityWolfNotAmused** [comment]
PS: Is the discord bot running on the same system as the servers?

**Comment by Tesch1933** [comment]
Thanks a lot!
Mainly server operators who run their server locally (at home) are affected. Most Internet providers assign users a new IP address every 24 hours. 

Yes, the Discord bot is running on the same system as the servers

**Comment by GravityWolfNotAmused** [comment]
Hm, I've looked for many ways to properly get your external IP address, it's possible, but it might be jank, but won't know if I don't try. I'll tag my changes to a branch, and the pull request, and at that point I will need your help to test, are you okay with this?

**Comment by Tesch1933** [comment]
Okay!
I'll support you as best I can and gladly take my time.

**Comment by GravityWolfNotAmused** [comment]
I have added the hostname branch that aims to provide you the solution to the dynamic IP.

The pull request is located:
https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/pull/6

Runnable files are located at the bottom of the pull request, or here:
[DiscordPlayerCountBot.zip](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/files/6333298/DiscordPlayerCountBot.zip)

**Comment by GravityWolfNotAmused** [comment]
Please let me know if it works for you, and read the messages of the pull request in order to use the feature.

**Comment by Tesch1933** [comment]
The Discord-BOT did not display the number of players.

It displays:
"Startong Bot watching: hostname:27016"

If i enter the current ip address:27016 of the server instead of "hostname", everything works fine

These are my current settings:

{
"_serverInformation": [
{
"botName": "Player on Server",
"botAddress": "hostname:27016",
"discordBotToken": "XXX"
}
],
"_updateTime": 30,
"_steamAPIKey": "XXX",
"_isDebug": false,
"_userConfigNameAsLabel": false
}

**Comment by GravityWolfNotAmused** [comment]
Pushed
