### ISSUE TITLE
[BUG] Instructions unclear, no .exe exists to begin installation?

### ISSUE THREAD

**Issue by rzm25** [GravityWolfNotAmused/PlayerCountDiscordBot#69]
The documentation advises when beginning to run the bot via an .exe in the /bin/ folder. However this doesn't exist in the release .zip download, and your installation instructions make no mention of how to create it? 

I know there is probably an obvious solution to lifelong coders but to people with little experience like myself there seems to be no clear explanation.

Furthermore, all the other tutorial pages in the documentation show screenshots of code, with no mention of what file the code is in, or how to create said file. I am assuming, based on my use of previous releases, that this is a config.json created after the first run of the bot - but again, the only installation instructions seems to say "run a .exe" that doesn't exist in the main .zip download of this repository.

**Comment by GravityWolfNotAmused** [comment]
What OS are you trying to use?

**Comment by GravityWolfNotAmused** [comment]
Releases are here: https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/releases

**Comment by GravityWolfNotAmused** [comment]
Can you point me to the faulty documentation, so I may fix it?

**Comment by rzm25** [comment]
Thanks for the quick response! 
Apologies in advance if, like I said, I'm missing something very obvious here. 

I am following the documentation found at [this page](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/wiki).

Based on the way it is written, I am assuming I am meant to start with the second last link, "[standard installation](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/wiki/Standard-Installation)". I come to this conclusion due to the fact that the first links, (i.e. "[Configuring a server](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/wiki/Configuring-Servers)") immediately starts by referring to screenshots of code that I do not have, without any instruction on where to input these options. 

So I follow the standard installation instructions. First, I download and install the runtime. Then the instructions say:

> After installation of .Net Runtime 6, you need to run the application one time.

There is no mention of what application, or where. However the provided screenshot shows a filepath:

> PlayerCountDiscordBot\DiscordPlayerCountBot\bin\Debug\net6.0\DiscordPlayerCountBot.exe

However I do not have any bin folder. 
![image](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/assets/5588902/6f842b93-35af-422b-b242-93ed37e1d443)

None of the other documentation pages seem to make any mention of how or where this bin folder comes from.

I am using the code from 'PlayCountDiscordBot-latest.zip', downloaded today. 

Thanks for your time.

**Comment by rzm25** [comment]
Ok I've just realised I must have downloaded the source code instead of the latest release.

Sorry to waste your time!

**Comment by GravityWolfNotAmused** [comment]
This was going to be my follow-up response, no worries.

**Comment by rzm25** [comment]
Thanks again
Commenting to close
