### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ggvix** [GravityWolfNotAmused/PlayerCountDiscordBot#9]
**Describe the bug**
For some reason it's not working properly for me, all I get is this:
![image](https://user-images.githubusercontent.com/70199669/144740336-b3bac31c-38a2-4436-9be1-e680c29e2641.png)

**To Reproduce**
1. Configure everything as it is supposed to be: 
![image](https://user-images.githubusercontent.com/70199669/144740268-e74ffbaf-d7c7-4f64-ae3a-2426e9e4e693.png)

2. After running it, Observing the console it seems it's getting responses from the server but it doesn't work as shown on the first provided screenshot.
![image](https://user-images.githubusercontent.com/70199669/144740147-c69cbb6c-ddbc-42b4-b8ee-68cbc85043b6.png)

No error messages. just doesn't work as it should.

 - OS: Windows 10

**Comment by GravityWolfNotAmused** [comment]
@ggvix Your query port is 2512, not 2502.
![image](https://user-images.githubusercontent.com/24533882/144783548-7ce583d6-c35e-4c05-bf54-23a957fa6dbc.png)

**Comment by GravityWolfNotAmused** [comment]
https://www.battlemetrics.com/servers/dayz/2992261

**Comment by ggvix** [comment]
Now I see what I was doing wrong. That's cool. That's the o ly info I can get from the server? Can't I get for example in-game time?

**Comment by GravityWolfNotAmused** [comment]
I have the ability to get time information with a different API; however, this would make the bot specific for DayZ which would limit the scope of who wishes to use it. Steam doesn't hold onto much more than generic server information.

This was suggested in my discord, and I may have to make a DayZ specific bot in the future; however, I would have to ask permission from the other API.

**Comment by ggvix** [comment]
Cool. Let me know if you are going ahead with this dayz bot project. I really appreciate it.
